#cloud-config

package_update: true

package_upgrade: true

users:
  - default
  - name: root
    shell: /bin/bash

packages:
  - wget
  - git
  - curl
  - ufw
  - gcc
  - make
  - nginx
  - certbot
  - python-certbot-nginx

write_files:
  - path: /etc/systemd/system/meilisearch.service
    content: |
      [Unit]
      Description=MeiliSearch
      After=systemd-user-sessions.service

      [Service]
      Type=simple
      ExecStart=/usr/bin/meilisearch --db-path /var/lib/meilisearch/data.ms --env development
      Environment="MEILI_SERVER_PROVIDER=gcp"

      [Install]
      WantedBy=default.target

  - path: /etc/nginx/sites-enabled/meilisearch
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;

          server_name _;

          location / {
              proxy_pass  http://127.0.0.1:7700;
          }

          client_max_body_size 100M;
      }
  
  - path: /etc/nginx/sites-enabled/default
    content: |
      # Empty file

  - path: /etc/profile.d/00-aliases.sh
    content: |
      alias meilisearch-setup='sudo sh /var/opt/meilisearch/scripts/first-login/000-set-meili-env.sh'

  - path: /etc/profile.d/01-auto-run.sh
    content: |
      meilisearch-setup

runcmd:
  - wget --directory-prefix=/usr/bin/ -O /usr/bin/meilisearch https://github.com/meilisearch/MeiliSearch/releases/download/v0.21.0/meilisearch-linux-amd64
  - chmod 755 /usr/bin/meilisearch
  - systemctl enable meilisearch.service
  - ufw --force enable
  - ufw allow 'Nginx Full'
  - ufw allow 'OpenSSH'
  - curl https://raw.githubusercontent.com/meilisearch/cloud-scripts/v0.21.0/scripts/deploy-meilisearch.sh | bash -s v0.20.0

power_state:
  mode: reboot
  message: Bye Bye
  timeout: 10
  condition: True
